# Generated by Django 3.2.4 on 2021-06-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefun', models.ImageField(upload_to='happy/')),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
