# Generated by Django 3.2.4 on 2021-06-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job1',
            old_name='imagefun',
            new_name='image',
        ),
    ]
