# Generated by Django 3.2.4 on 2021-06-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_rename_blog2_blog1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog1',
            new_name='blog2',
        ),
    ]
